### ISSUE TITLE
Fix broken unit test(s) at 80d146a

### ISSUE THREAD

**Issue by danwt** [cosmos/interchain-security#165]
At 80d146a02b0b7631a01cd40f026e6609ccb2f3d9 the CI tests fail on github

**Comment by danwt** [comment]
The same commit is now showing as passing on the CI so I wonder if there is a flaky test. Closing for now, reopen if it shows up again.

**Comment by danwt** [comment]
Reopening:

I think there is a flaky test at 0fa770d

https://github.com/cosmos/interchain-security/blob/335bd7c17fa5a9b33db25e44ddccfa899d675328/x/ccv/provider/keeper/proposal_test.go#L116-L146

```bash
--- FAIL: TestKeeperTestSuite (0.28s)
    --- FAIL: TestKeeperTestSuite/TestIteratePendingStopProposal (0.01s)
        suite.go:63: test panicked: runtime error: index out of range [7] with length 4
            goroutine 3029 [running]:
            runtime/debug.Stack()
            	/opt/homebrew/Cellar/go/1.18.1/libexec/src/runtime/debug/stack.go:24 +0x68
            github.com/stretchr/testify/suite.failOnPanic(0x140018ba4e0)
            	/Users/danwt/go/pkg/mod/github.com/stretchr/testify@v1.7.0/suite/suite.go:63 +0x40
            panic({0x105e12e40, 0x14001759158})
            	/opt/homebrew/Cellar/go/1.18.1/libexec/src/runtime/panic.go:838 +0x204
            encoding/binary.bigEndian.Uint64(...)
            	/opt/homebrew/Cellar/go/1.18.1/libexec/src/encoding/binary/binary.go:125
            github.com/cosmos/interchain-security/x/ccv/provider/keeper.Keeper.IteratePendingStopProposal({{0x105f12d20, 0x14000031760}, {0x105f2f4d8, 0x14000ebed90}, {{0x105f2f4d8, 0x14000ebed90}, 0x1400179a290, {0x105f12d20, 0x14000031680}, {0x105f12d70, ...}, ...}, ...}, ...)
            	/Users/danwt/Documents/work/interchain-security/x/ccv/provider/keeper/proposal.go:316 +0x498
            github.com/cosmos/interchain-security/x/ccv/provider/keeper_test.(*KeeperTestSuite).TestIteratePendingStopProposal(0x14000f2c780)
            	/Users/danwt/Documents/work/interchain-security/x/ccv/provider/keeper/proposal_test.go:140 +0x344
            reflect.Value.call({0x105c745c0?, 0x14000bf9560?, 0x0?}, {0x105701196, 0x4}, {0x140004dde68, 0x1, 0x0?})
            	/opt/homebrew/Cellar/go/1.18.1/libexec/src/reflect/value.go:556 +0x5e4
            reflect.Value.Call({0x105c745c0?, 0x14000bf9560?, 0x14000f2c780?}, {0x140004dde68, 0x1, 0x1})
            	/opt/homebrew/Cellar/go/1.18.1/libexec/src/reflect/value.go:339 +0x98
            github.com/stretchr/testify/suite.Run.func1(0x140018ba4e0)
            	/Users/danwt/go/pkg/mod/github.com/stretchr/testify@v1.7.0/suite/suite.go:158 +0x3e8
            testing.tRunner(0x140018ba4e0, 0x14000fd9e60)
            	/opt/homebrew/Cellar/go/1.18.1/libexec/src/testing/testing.go:1439 +0x110
            created by testing.(*T).Run
            	/opt/homebrew/Cellar/go/1.18.1/libexec/src/testing/testing.go:1486 +0x300
```

**Comment by danwt** [comment]
I just triple checked for sanity. Indeed flaky on master (335bd7c17fa5a9b33db25e44ddccfa899d675328). Will try to fix.

**Comment by danwt** [comment]
`TestIteratePendingClientInfo` also fails flakily

```
--- FAIL: TestKeeperTestSuite (0.26s)
    --- FAIL: TestKeeperTestSuite/TestIteratePendingClientInfo (0.01s)
        suite.go:63: test panicked: runtime error: index out of range [7] with length 5
            goroutine 2748 [running]:
            runtime/debug.Stack()
            	/opt/homebrew/Cellar/go/1.18.1/libexec/src/runtime/debug/stack.go:24 +0x68
            github.com/stretchr/testify/suite.failOnPanic(0x14001a0e680)
            	/Users/danwt/go/pkg/mod/github.com/stretchr/testify@v1.7.0/suite/suite.go:63 +0x40
            panic({0x1047cee40, 0x14001a99e18})
            	/opt/homebrew/Cellar/go/1.18.1/libexec/src/runtime/panic.go:838 +0x204
            encoding/binary.bigEndian.Uint64(...)
            	/opt/homebrew/Cellar/go/1.18.1/libexec/src/encoding/binary/binary.go:125
            github.com/cosmos/interchain-security/x/ccv/provider/keeper.Keeper.IteratePendingClientInfo({{0x1048ced20, 0x1400171cc70}, {0x1048eb4d8, 0x14001690eb0}, {{0x1048eb4d8, 0x14001690eb0}, 0x140004f1828, {0x1048ced20, 0x1400171cbe0}, {0x1048ced70, ...}, ...}, ...}, ...)
            	/Users/danwt/Documents/work/interchain-security/x/ccv/provider/keeper/proposal.go:245 +0x4e4
            github.com/cosmos/interchain-security/x/ccv/provider/keeper_test.(*KeeperTestSuite).TestIteratePendingClientInfo(0x1400103b180)
            	/Users/danwt/Documents/work/interchain-security/x/ccv/provider/keeper/proposal_test.go:173 +0x384
            reflect.Value.call({0x1046305c0?, 0x140012ca098?, 0x0?}, {0x1040bd196, 0x4}, {0x1400145de68, 0x1, 0x0?})
            	/opt/homebrew/Cellar/go/1.18.1/libexec/src/reflect/value.go:556 +0x5e4
            reflect.Value.Call({0x1046305c0?, 0x140012ca098?, 0x1400103b180?}, {0x1400145de68, 0x1, 0x1})
            	/opt/homebrew/Cellar/go/1.18.1/libexec/src/reflect/value.go:339 +0x98
            github.com/stretchr/testify/suite.Run.func1(0x14001a0e680)
            	/Users/danwt/go/pkg/mod/github.com/stretchr/testify@v1.7.0/suite/suite.go:158 +0x3e8
            testing.tRunner(0x14001a0e680, 0x140010c3050)
            	/opt/homebrew/Cellar/go/1.18.1/libexec/src/testing/testing.go:1439 +0x110
            created by testing.(*T).Run
            	/opt/homebrew/Cellar/go/1.18.1/libexec/src/testing/testing.go:1486 +0x300
```

**Comment by danwt** [comment]
The problem(s) seems to be here

https://github.com/cosmos/interchain-security/blob/335bd7c17fa5a9b33db25e44ddccfa899d675328/x/ccv/provider/keeper/proposal.go#L245

https://github.com/cosmos/interchain-security/blob/335bd7c17fa5a9b33db25e44ddccfa899d675328/x/ccv/provider/keeper/proposal.go#L316

**Comment by danwt** [comment]
I think the bug occurs because in the key creation

https://github.com/cosmos/interchain-security/blob/335bd7c17fa5a9b33db25e44ddccfa899d675328/x/ccv/provider/types/keys.go#L124-L129

`fmt.Sprintf("%s/%s/%s", PendingClientKeyPrefix, timeBytes, chainID))` can format any of the fields `PendingClientKeyPrefix, timeBytes, chainID` to contain a byte which is the same as `/`. Therefore when parsing

https://github.com/cosmos/interchain-security/blob/335bd7c17fa5a9b33db25e44ddccfa899d675328/x/ccv/provider/keeper/proposal.go#L243

additional `/` characters can be present!

**Comment by danwt** [comment]
Replacement issue

https://github.com/cosmos/interchain-security/issues/186
